# Generated by Django 3.0.4 on 2020-04-08 08:07

import Mediafiles.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=Mediafiles.models.directory_path, validators=[django.core.validators.validate_image_file_extension])),
                ('object_id', models.PositiveIntegerField()),
                ('object_type', models.CharField(choices=[('place', 'place'), ('gpin', 'gpin'), ('ppin', 'ppin'), ('achievement', 'achievement'), ('user', 'user')], max_length=32)),
                ('created_by', models.PositiveIntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('deleted_flg', models.BooleanField(default=False)),
            ],
        ),
    ]
