# Generated by Django 3.0.4 on 2020-04-08 08:16

import Mediafiles.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefiles',
            name='image',
            field=models.ImageField(upload_to=Mediafiles.models.directory_path, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
